apiVersion: v1
kind: Service
metadata:
  name: emqx-service
spec:
  selector:
    app: emqx
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mqtt-web
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: management
      protocol: TCP
      port: 18083
      targetPort: 18083
