apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-task
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react-task
  template:
    metadata:
      labels:
        app: react-task
    spec:
      containers:
      - name: react-task
        image: 1pooja1/react-task
        ports:
        - containerPort: 3000
