# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: react-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - host: pooja-shrestha.com.np
#     http:
#       paths:
#       - path: /static
#         pathType: Prefix
#         backend:
#           service:
#             name: react-task-service
#             port:
#               number: 3000
