apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: treeleaf
spec:
  type: NodePort
  selector:
    app: treeleaf
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
