apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2
spec:
  selector:
    matchLabels:
      app: task2
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
      - name: task2
        image: 1pooja1/task2
        ports:
        - containerPort: 8080
